name: social_app_tdd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  bloc: ^8.1.0  
  cloud_firestore: ^4.6.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_offline: ^2.1.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3
  get_it: ^7.2.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+11
  injectable: ^2.1.2
  internet_connection_checker: any
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
