// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJGoGUPi-MPi2Rmws6w-i3goMjVBJ_uQ',
    appId: '1:698111053998:web:9a927f114512e672285d3f',
    messagingSenderId: '698111053998',
    projectId: 'social-app-tdd',
    authDomain: 'social-app-tdd.firebaseapp.com',
    storageBucket: 'social-app-tdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbHL5vZwKjTTQn1EcL_9NhqZV0EcR78I',
    appId: '1:698111053998:android:485803fe4071d9a2285d3f',
    messagingSenderId: '698111053998',
    projectId: 'social-app-tdd',
    storageBucket: 'social-app-tdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmHTYphFo71p3dCh9NrCu-SSc-q_GumQ',
    appId: '1:698111053998:ios:fa5483bcee113e60285d3f',
    messagingSenderId: '698111053998',
    projectId: 'social-app-tdd',
    storageBucket: 'social-app-tdd.appspot.com',
    iosClientId: '698111053998-ecretc8ilf1lg2ig72jsh799tlbe54rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppTdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdmHTYphFo71p3dCh9NrCu-SSc-q_GumQ',
    appId: '1:698111053998:ios:fa5483bcee113e60285d3f',
    messagingSenderId: '698111053998',
    projectId: 'social-app-tdd',
    storageBucket: 'social-app-tdd.appspot.com',
    iosClientId: '698111053998-ecretc8ilf1lg2ig72jsh799tlbe54rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppTdd',
  );
}
